### ISSUE TITLE
Конфигуриране на потребител

### ISSUE THREAD

**Issue by vtzarkov** [Nedevski/hass_kat_bulgaria#2]
Липсва информация как се конфигурират потребителите

**Comment by Nedevski** [comment]
Ок, ще подобря документацията когато имам време. Дотогава оставям тикета отворен.

Бързи инструкции:
1. Трябва да има инсталиран [HACS](https://hacs.xyz/)
2. HACS => Integrations
3. Долу вдясно => "Explore & download repositories"
4. Търсене за "KAT Bulgaria" и добавяне
5. Рестарт на HomeAssistant
6. Добавяне на KAT Bulgaria като стандартна интеграция (Devices & Services => Add integration)
7. Следване на инструкциите в прозореца
