### ISSUE TITLE
Error Setup

### ISSUE THREAD

**Issue by ValeriGYordanov** [Nedevski/hass_kat_bulgaria#3]
**Describe the bug**
When trying to setup the extension I do get an unknown error after providing my details.

**To Reproduce**
1. Go to Home Assistant add integration
2. Search and Chose "KAT Bulgaria"
3. Add details and click next.

**Expected behavior**
The integration should be added successfully

**Additional context**
The error that I got

File "/usr/local/lib/python3.11/site-packages/kat_bulgaria/obligations.py", line 294, in __get_obligations_request
    raise KatError(
kat_bulgaria.obligations.KatError: [KAT_API] Website returned a malformed response: {'obligationsData': [{'unitGroup': 1, 'errorNoDataFound': False, 'errorReadingData': False, 'obligations': []}, {'unitGroup': 2, 'errorNoDataFound': False, 'errorReadingData': False, 'obligations': []}]}

**Comment by Nedevski** [comment]
Unfortunately KAT changed their whole system so this whole library/integration have to be rewritten from scratch.

An added inconvenience is that I'm not sure if the already seen obligations aren't counted as "served", meaning you have 2 weeks to pay with discount.
